In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import statsmodels.formula.api as smf

In [2]:
df = pd.read_csv("mtcars.csv")
df.head()
df.shape

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

(32, 12)

In [3]:
# Fit a linear regression model with multiplicative interactions
model = smf.ols("mpg ~ hp * wt * am", data=df).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.866
Method:                 Least Squares   F-statistic:                     29.55
Date:                Sat, 01 Jun 2024   Prob (F-statistic):           2.60e-10
Time:                        18:33:04   Log-Likelihood:                -66.158
No. Observations:                  32   AIC:                             148.3
Df Residuals:                      24   BIC:                             160.0
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     40.3272     13.008      3.100      0.005      13.480      67.175
hp            -0.0888      0.065     -1.372      0.183      -0.222       0.045
wt            -4.7968      4.002     -1.199      0.242     -13.056       3.462
hp:wt          0.0145      0.019      0.755      0.458      -0.025       0.054
am            12.8371     14.222      0.903      0.376     -16.517      42.191
hp:am         -0.0326      0.089     -0.366      0.717      -0.216       0.151
wt:am         -5.3620      4.597     -1.166      0.255     -14.851       4.127
hp:wt:am       0.0178      0.026      0.680      0.503      -0.036       0.072
==============================================================================
Omnibus:                        1.875   Durbin-Watson:                   2.205
Prob(Omnibus):                  0.392   Jarque-Bera (JB):                1.588
Skew:                           0.528   Prob(JB):                        0.452
Kurtosis:                       2.721   Cond. No.                     3.32e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.32e+04. This might indicate that there are
strong multicollinearity or other numerical problems.